### ISSUE TITLE
Rate indicator in [Counter] is not updated

### ISSUE THREAD

**Issue by hollyhook** [still-scene/t3#71] opened 2022-07-22 08:30 UTC
Minor bug in [Counter] operator
If countrolled from outside, the rate number in isn't updated

![image](https://user-images.githubusercontent.com/9899825/180397825-0fe4f683-a341-4f9a-849d-f0a06eb88927.png)

In the example the rate is displayed as, 1.4, expected would be 15.99.
Only the display is wrong, the rate is correctly changed.

**Comment by domportera** [comment] 2022-09-20 08:52
note: looked into this, it looks like any operator with a Rate input slot doesn't work properly in this way. getting the Rate's TypedInputValue always returns a 1.0 in the DrawChildUi function

**Comment by hollyhook** [comment] 2022-09-20 17:12
Maybe it not updated for performance reasons ... but it should take away the 1.4 anyway

**Comment by pixtur** [comment] 2022-09-21 19:48
@hollyhook Thanks for reporting this. I can reproduce the issue and it should be fixed in next version.

**Closed by pixtur** 2022-09-21 19:48 UTC
