### ISSUE TITLE
Applying backup causes error and hinders launch

### ISSUE THREAD

**Issue by MaxiWH** [still-scene/t3#36] opened 2022-06-28 14:28 UTC
**Describe the bug**
After unzipping a backup into a clean (newly downloaded and unzipped) version of the preview stand-alone 3.2.2 and launching t3.exe the console ends up throwing an error and the application does not launch. 

**Please complete the following information):**
 - OS: Windows 10
 - Version: 21H2
 - Graphics card and resolution: NVIDIA GeForce GTX 1070 - 1920 x 1080

**To Reproduce**
Steps to reproduce the behaviour:
1. Download the stand-alone preview version 3.2.2 (found [here](https://github.com/still-scene/t3/releases/v3.2.0))
2. Unzip it
3. Download [this ](https://drive.google.com/file/d/1_Rve9kGi-LKEcFArWmDzYXMuyCIj0Eeb/view?usp=sharing) backup file and place it in the T3Editor folder
4. Unzip the backup folder and overwrite any existing files
5. Launch t3.exe
6. An error is thrown in the console window and the application does not launch

**Expected behaviour**
The expected behaviour is that the application would launch with the nodes included in the backup.

**Screenshots**
Here's a screenshot of the error that is shown in the console window before it closes
![bild](https://user-images.githubusercontent.com/72453520/176202499-a33749c1-e1d8-46b7-ab27-45e19a2fe193.png)

**Additional context**
[Here ](https://drive.google.com/file/d/1E4XkvBZleAbtic2dl8Dv_JyCpElM_QYu/view?usp=sharing) is the log which was generated after the error occurred

**Comment by pixtur** [comment] 2022-06-28 17:48
Excellent report! I'm going to look into it.
Sadly, your Backup is probably incomplete and can be used because there is a new Symbol "Repulsion" that is not fully exported. I assume they if you delete the three files with that ID, Tooll will start but all instances of that op will be missing.

We have to identify how to reproduce what causes the backup to be incomplete.

- Can you check, if the 3 files with the ID existing in your ` Operators/Types/` folder? And if they have a non-zero size?
- You you check if other backups have the same problem?

**Comment by MaxiWH** [comment] 2022-06-28 18:13
@pixtur 

There does exist 3 files within `Operators/Types/` and all of them have a non-zero size. Removing them did indeed allow the application to launch properly but without that op.

I have tried loading different backups from different stages of that same session and those created before the one I included in my report don't cause any errors when loaded.

**Comment by pixtur** [comment] 2022-07-15 18:17
I will close this issue for now. If the problem reoccurs please reopen and provide additional details.

**Closed by pixtur** 2022-07-15 18:17 UTC
Labels: bug
