### ISSUE TITLE
Crash when trying to use BeatDetectionExample

### ISSUE THREAD

**Issue by haysmike** [still-scene/t3#236] opened 2023-03-20 08:53 UTC
**Describe the bug**
Tooll crashes when trying to add BeatDetectionExample to the canvas

**Please complete the following information):**
 - OS: Windows 10
 - Version: 3.5.1 standalone
 - Graphics card and resolution: GTX 1080, 3840x1600

**To Reproduce**
1.Try to add `pixtur.examples.BeatDetectionExample` to canvas
2. Tooll evaporates

**Expected behavior**
Not crashing

**Screenshots**
![Tooll](https://user-images.githubusercontent.com/659447/226290256-6108c7ee-07c5-46a1-973f-683693b460d6.gif)

![image](https://user-images.githubusercontent.com/659447/226291224-ef703144-37c3-457a-9f1a-83521776a2f1.png)

**Additional context**
Maybe the example is storing some information about the audio setup that doesn't make sense on my system?

**Comment by pixtur** [comment] 2023-04-16 18:31
Thanks for report!

I can't reproduce the issue on the dev-branch. So it probably has been fixed on upcoming v3.6 release.

**Closed by pixtur** 2023-04-16 18:31 UTC
