### ISSUE TITLE
Can't animate bools

### ISSUE THREAD

**Issue by Fobo00** [still-scene/t3#35] opened 2022-06-28 10:58 UTC
**Describe the bug**

Bools stay constant in animation timeline and result

**Please complete the following information):**
 - OS: Windows
 - Version: 
 - Graphics card and resolution 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by pixtur** [comment] 2022-06-30 10:58
Booleans can be interpolated, when animated they will hold the last keyframe value until the next keyframe. This is by design.
As a work around you can use an operator that generates a boolean output like [CompareValue] and animate it's input.

**Comment by pixtur** [comment] 2022-07-01 16:32
A regression broke the expected behaviour. 
I'm sorry to close it before properly checking.

**Comment by pixtur** [comment] 2022-07-01 18:39
Should be fixed in next release

**Closed by pixtur** 2022-07-01 18:39 UTC
Labels: feature request, animation
